version: '3.8'

networks:
  pdf_network:
    driver: overlay
    attachable: true

services:
  pdf-scanner:
    image: thirdlaw-challenge-pdf-scanner:latest
    build: .
    networks:
      - pdf_network
    environment:
      - WORKERS=4
      - WORKER_CLASS=uvicorn.workers.UvicornWorker
    deploy:
      replicas: 6  # More replicas for higher throughput
      resources:
        limits:
          cpus: '1.5'  # More CPU per replica
          memory: 1.5G
        reservations:
          cpus: '1.0'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  load-balancer:
    image: nginx:alpine
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - pdf_network
    deploy:
      replicas: 1  # Single load balancer for less overhead
      resources:
        limits:
          cpus: '1.0'  # More CPU for NGINX
          memory: 512M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - pdf-scanner

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pdf_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=demo123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    networks:
      - pdf_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

configs:
  nginx_config:
    file: ./nginx.conf
  prometheus_config:
    file: ./prometheus.yml