global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Auto-scaling rules will be defined here
  # - "scaling_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PDF Scanner instances (auto-discovered via Docker Swarm)
  - job_name: 'pdf-scanner'
    dns_sd_configs:
      - names:
          - 'tasks.pdf-scanner'
        type: 'A'
        port: 8000
    metrics_path: '/metrics/prometheus'
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pdf-scanner:8000

  # Load balancer metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['load-balancer:80']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Container metrics for auto-scaling
  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Docker Swarm service discovery
  - job_name: 'docker-swarm'
    dockerswarm_sd_configs:
      - host: 'unix:///var/run/docker.sock'
        role: services
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: job
      - source_labels: [__meta_dockerswarm_service_name]
        regex: (.+)
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'localhost:9090'